package com.example.demo.security;

public enum PermissionType {

    // PATIENT
    VIEW_PATIENT,
    CREATE_PATIENT,
    UPDATE_PATIENT,
    DELETE_PATIENT,

    // REPORT
    VIEW_REPORT,
    DOWNLOAD_REPORT,
    EDIT_REPORT,

    // VITALS
    ENTER_VITALS,
    VIEW_VITALS,

    // DOCTOR
    UPDATE_DIAGNOSIS,
    ADD_PRESCRIPTION,
    DIGITAL_SIGN,
    REQUEST_LAB,
    APPROVE_DISCHARGE,
    VIEW_LAB_RESULTS,

    // NURSE
    ADD_NURSE_NOTES,
    UPDATE_PATIENT_STATUS,
    VIEW_DOCTOR_INSTRUCTION,
    MANAGE_SHIFT,

    // INVENTORY
    VIEW_MEDICINE_STOCK,
    UPDATE_MEDICINE_STOCK,

    // APPOINTMENT
    BOOK_APPOINTMENT,
    VIEW_APPOINTMENT,

    // ADMIN
    CREATE_USER,
    UPDATE_USER,
    DELETE_USER,
    VIEW_AUDIT_LOG
}

